language: node_js
node_js:
  - 15.2.0
env:
  - NPM_TOKEN=${{NPM_TOKEN}}
  - CODECOV_TOKEN=${{COVER_TOKEN}}
install:
  - npm install
  - npm install codecov -g

script:
  - npm run test
  - codecov --token=$CODECOV_TOKEN
  - npm run build
  - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
  - npm publish